server:
  port: 8081
spring:
  application:
    name: merchant-service
  datasource:
    url: jdbc:h2:mem:merchant_db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
