apiVersion: v1
kind: ConfigMap
metadata:
  name: paypilot-config
  namespace: {{ include "paypilot.namespace" . }}
  labels:
{{ include "paypilot.labels" . | nindent 4 }}
data:
  MERCHANT_SERVICE_URL: http://{{ .Values.services.merchant.name }}:{{ .Values.services.merchant.port }}
  PAYMENT_SERVICE_URL: http://{{ .Values.services.payment.name }}:{{ .Values.services.payment.port }}
  LEDGER_SERVICE_URL: http://{{ .Values.services.ledger.name }}:{{ .Values.services.ledger.port }}
  FEATURE_SETTLEMENT_EXPORT: {{ .Values.config.featureSettlementExport | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: paypilot-db-secret
  namespace: {{ include "paypilot.namespace" . }}
  labels:
{{ include "paypilot.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.database.username | quote }}
  password: {{ .Values.database.password | quote }}
